### ISSUE TITLE
Why limiting to create, read, update, delete?

### ISSUE THREAD

**Issue by robink** [yahoo/fluxible-plugin-fetchr#15]
It seems that the plugin is locking the hard way the fact that you must only use 'create', 'read', 'update, 'delete'. I find that very restrictive. 

If we have the following ressource: blog_post

You can create, read, update and delete a blog post.

But how would you: 
- list all blog posts (i.e. use another kind of operation on the ressource)
- share by email a blog post (i.e. do an action on the ressource)

Thanks !

**Comment by robink** [comment]
I just came across this issue: https://github.com/yahoo/fetchr/issues/33

So, this limitation is a *feature*. But then, how would you achieve what I described? 
Do you create multiple services for the same ressource (like `blog_post` for single items, `blog_posts` for manipulating collections and `blog_post_sharing` for executing any kind of share action) or do the "read", "create", "delete", “update" act as hub for other actions (like `read` will call `list` method if no argument is provided or will call `show` method if params `id` is provided) ?

**Comment by jedireza** [comment]
Thanks for opening an issue. In the [todo example](https://github.com/yahoo/flux-examples) we take action on all todos by appending `.something` to the service name and checking for this on the resource argument.

Here you can see how instead of just `todo` we use `todo.toggleAll` in the action:

 - https://github.com/yahoo/flux-examples/blob/master/todo/actions/toggleAll.js#L11

And here we're changing our behavior in the service based on that:

 - https://github.com/yahoo/flux-examples/blob/master/todo/services/todo.js#L43

**Comment by robink** [comment]
:+1: 

Thanks a lot for the response, it's making much more sense to me now.  :)

**Comment by mlennon3** [comment]
:+1: Really helpful!

**Comment by pjvds** [comment]
Just for reference, here are the updated links from @jedireza:

Here you can see how instead of just todo we use todo.toggleAll in the action:

 

- https://github.com/yahoo/fluxible/blob/master/examples/todo/actions/toggleAll.js#L11


And here we're changing our behavior in the service based on that:

- https://github.com/yahoo/fluxible/blob/master/examples/todo/services/todo.js#L43
