### ISSUE TITLE
Where is used fetchr.client.js?

### ISSUE THREAD

**Issue by davide-ganito** [yahoo/fluxible-plugin-fetchr#9]
Hi,
i'm trying to use fetchr as a fluxible plugin in my project but i can't make it work from client to server.
I red the code, I can't find where are used fetcher.client.js functions to make xhrRequest.
Practically i can't see any implementation difference between server and client side of the plugin.

Can someone help me with this?
Thanks!

**Comment by jedireza** [comment]
Have you checked out our [flux-examples](https://github.com/yahoo/flux-examples/) repo? We have some working examples.

The `fetcher.client.js` file is inside the [`fetchr`](https://github.com/yahoo/fetchr) module, which this plugin depends on. When `fetchr` is bundled for the browser it's [`package.json` file has a `browser` directive](https://github.com/yahoo/fetchr/blob/master/package.json#L6) which will use `fetcher.client.js` instead of the server side code.

Hope that helps.

**Comment by davide-ganito** [comment]
Thanks! It helped a lot.
Everything is working fine now!

Have a nice day!
